// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetWorld.Infrastructure.Data;

#nullable disable

namespace PetWorld.Infrastructure.Migrations
{
    [DbContext(typeof(PetWorldDbContext))]
    [Migration("20260202182656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PetWorld.Domain.Entities.ChatHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IterationCount")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ChatHistory");
                });

            modelBuilder.Entity("PetWorld.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Karma dla psów",
                            Description = "Premium karma dla dorosłych psów średnich ras",
                            Name = "Royal Canin Adult Dog 15kg",
                            Price = 289m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Karma dla kotów",
                            Description = "Sucha karma dla dorosłych kotów z kurczakiem",
                            Name = "Whiskas Adult Kurczak 7kg",
                            Price = 129m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Akwarystyka",
                            Description = "Uzdatniacz wody do akwarium, neutralizuje chlor",
                            Name = "Tetra AquaSafe 500ml",
                            Price = 45m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Akcesoria dla kotów",
                            Description = "Wysoki drapak z platformami i domkiem",
                            Name = "Trixie Drapak XL 150cm",
                            Price = 399m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Zabawki dla psów",
                            Description = "Wytrzymała zabawka do napełniania smakołykami",
                            Name = "Kong Classic Large",
                            Price = 69m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Gryzonie",
                            Description = "Klatka 60x40cm z wyposażeniem",
                            Name = "Ferplast Klatka dla gryzonia",
                            Price = 189m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Akcesoria dla psów",
                            Description = "Smycz zwijana dla psów do 50kg",
                            Name = "Flexi Smycz automatyczna 8m",
                            Price = 119m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Karma dla kotów",
                            Description = "Karma dla kociąt do 12 miesiąca życia",
                            Name = "Brit Premium Kitten 8kg",
                            Price = 159m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Akwarystyka",
                            Description = "Kompletny zestaw CO2 dla roślin akwariowych",
                            Name = "JBL ProFlora CO2 Set",
                            Price = 549m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Gryzonie",
                            Description = "Naturalne siano łąkowe, podstawa diety",
                            Name = "Vitapol Siano dla królików 1kg",
                            Price = 25m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
